---
- hosts: all
  become: true
  tasks:

  # - name: Désinstallation des packages
  #   shell:
  #     cmd: apt-get purge apache2 git

  - name: Désinstallation des packages
    apt:
      purge: yes
      name:
        - git
        - nodejs
        - npm
        - apache2
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - apt-transport-https
        - ca-certificates
        - wget
        - software-properties-common
        - gnupg2
        - curl
        - apt-transport-https
        - gnupg
        - lsb-release
      
      update_cache: yes